@startuml
left to right direction
actor "Blogueur" as fc

actor "Visiteur" as visiteur
rectangle "Fonctionnalités" {
  usecase "CRUD articles" as UC1
 
  usecase "CRUD Catégories" as UC2 
 
  usecase "Consulter articles" as UC3


  

}
fc -- UC1
visiteur -- UC3

fc -- UC2



@enduml
